flags:
  hakyll:
    previewserver: false
    checkexternal: false
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
system-ghc: true
extra-deps:
- JuicyPixels-3.2.8
- SHA-1.6.4.2
- aeson-0.11.2.1
- aeson-pretty-0.8.2
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- asn1-encoding-0.9.4
- asn1-parse-0.9.4
- asn1-types-0.3.2
- base-compat-0.9.1
- base64-bytestring-1.0.0.1
- blaze-builder-0.4.0.2
- blaze-html-0.8.1.3
- blaze-markup-0.7.1.1
- byteable-0.1.1
- cereal-0.5.4.0
- clay-0.11
- cmark-0.5.4
- cmdargs-0.10.14
- conduit-1.2.8
- conduit-extra-1.1.15
- connection-0.2.6
- contravariant-1.4
- cookie-0.4.2.1
- cryptohash-0.11.9
- cryptonite-0.20
- data-default-0.7.1.1
- data-default-class-0.1.2.0
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- digest-0.0.1.2
- dlist-0.8.0.2
- enclosed-exceptions-1.0.2
- exceptions-0.8.3
- extensible-exceptions-0.1.1.4
- fail-4.9.0.0
- filemanip-0.3.6.3
- fsnotify-0.2.1
- haddock-library-1.4.2
- hakyll-4.9.1.0
- highlighting-kate-0.6.3
- hinotify-0.3.8.1
- hourglass-0.2.10
- hs-bibutils-5.5
- hslua-0.4.1
- http-client-0.5.4
- http-client-tls-0.3.3
- http-types-0.9.1
- lifted-base-0.2.3.8
- lrucache-1.2.0.0
- memory-0.13
- mime-types-0.1.0.7
- mmorph-1.0.9
- monad-control-1.0.1.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- optparse-applicative-0.13.0.0
- pandoc-1.17.2
- pandoc-citeproc-0.10.2.2
- pandoc-types-1.16.1.1
- pem-0.2.2
- regex-pcre-builtin-0.94.4.8.8.35
- regex-tdfa-1.2.2
- resourcet-1.1.8.1
- rfc5051-0.1.0.3
- semigroups-0.18.2
- setenv-0.1.1.3
- socks-0.5.5
- streaming-commons-0.1.16
- system-filepath-0.4.13.4
- tagged-0.8.5
- tagsoup-0.14
- temporary-1.2.0.4
- texmath-0.8.6.7
- time-locale-compat-0.1.1.3
- tls-1.3.8
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unix-compat-0.4.2.0
- utf8-string-1.0.1.1
- void-0.7.1
- x509-1.6.4
- x509-store-1.6.2
- x509-system-1.6.4
- x509-validation-1.6.5
- xml-1.3.14
- xml-conduit-1.4.0.2
- xml-types-0.3.6
- yaml-0.8.21
- zip-archive-0.3.0.5
resolver: ghc-8.0.2
allow-newer: true
